[www]
pm = ondemand
pm.max_children = 2
pm.process_idle_timeout = 10s
pm.max_requests = 100

php_admin_value[memory_limit] = 96M
php_admin_value[post_max_size] = 12M
php_admin_value[upload_max_filesize] = 8M
